// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/clinic-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
var clinic_info_default = defineTool({
  name: "clinic_info",
  title: "Informa\xE7\xF5es da cl\xEDnica",
  description: "Retorna dados de contato, endere\xE7o e hor\xE1rios de atendimento do consult\xF3rio da Dra. Bruna Durelli.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      medica: "Dra. Bruna Durelli",
      especialidade: "Medicina metab\xF3lica, endoscopia bari\xE1trica e medicina regenerativa",
      whatsapp: "(11) 99702-3024",
      whatsapp_link: "https://wa.me/5511997023024",
      email: "contato@brunadurelli.com.br",
      endereco: "Av. Brasil, 173 - Jardim Paulista, S\xE3o Paulo - SP, 01431-000",
      horarios: {
        semana: "Seg a Sex: 8h \xE0s 18h",
        sabado: "S\xE1b: 8h \xE0s 12h"
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-treatments.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
var TREATMENTS = [
  {
    slug: "balao-intragastrico",
    nome: "Bal\xE3o Intrag\xE1strico",
    resumo: "Procedimento endosc\xF3pico sem cortes que reduz o volume g\xE1strico e ajuda no emagrecimento com acompanhamento multidisciplinar.",
    path: "/balao-intragastrico"
  },
  {
    slug: "gastroplastia-endoscopica",
    nome: "Gastroplastia Endosc\xF3pica",
    resumo: "Sutura endosc\xF3pica do est\xF4mago (sleeve endosc\xF3pico) para redu\xE7\xE3o de capacidade g\xE1strica sem cirurgia aberta.",
    path: "/gastroplastia-endoscopica"
  },
  {
    slug: "canetas-emagrecedoras",
    nome: "Canetas Emagrecedoras",
    resumo: "Terapia saciet\xF3gena com medica\xE7\xF5es injet\xE1veis, sempre com indica\xE7\xE3o e acompanhamento m\xE9dico.",
    path: "/canetas-emagrecedoras"
  },
  {
    slug: "medicina-regenerativa",
    nome: "Medicina Regenerativa",
    resumo: "Protocolos de regenera\xE7\xE3o metab\xF3lica e celular voltados a energia, longevidade e recupera\xE7\xE3o funcional.",
    path: "/medicina-regenerativa"
  },
  {
    slug: "plasma-argonio",
    nome: "Plasma de Arg\xF4nio",
    resumo: "Tratamento endosc\xF3pico indicado em casos de reganho de peso ap\xF3s cirurgia bari\xE1trica.",
    path: "/plasma-argonio"
  },
  {
    slug: "nutricao-celular",
    nome: "Nutri\xE7\xE3o Celular",
    resumo: "Abordagem nutricional focada em fun\xE7\xE3o mitocondrial, saciedade e reequil\xEDbrio metab\xF3lico.",
    path: "/nutricao-celular"
  },
  {
    slug: "programa-levser",
    nome: "Programa LevSer",
    resumo: "Programa completo de transforma\xE7\xE3o metab\xF3lica com os quatro pilares: nutri\xE7\xE3o, metab\xF3lica/regenerativa, movimento e mente.",
    path: "/programa-levser"
  }
];
var list_treatments_default = defineTool2({
  name: "list_treatments",
  title: "Listar tratamentos",
  description: "Lista os tratamentos e programas oferecidos, com resumo e caminho da p\xE1gina no site.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(TREATMENTS, null, 2) }],
    structuredContent: { treatments: TREATMENTS }
  })
});

// src/lib/mcp/tools/estimate-bmi.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var estimate_bmi_default = defineTool3({
  name: "estimate_bmi",
  title: "Estimar IMC e faixa de risco",
  description: "Calcula o IMC a partir de peso e altura e retorna a faixa de classifica\xE7\xE3o e uma orienta\xE7\xE3o geral. N\xE3o substitui avalia\xE7\xE3o m\xE9dica.",
  inputSchema: {
    weight_kg: z.number().positive().describe("Peso em quilogramas."),
    height_cm: z.number().positive().describe("Altura em cent\xEDmetros."),
    waist_cm: z.number().positive().optional().describe("Circunfer\xEAncia abdominal em cent\xEDmetros (opcional).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ weight_kg, height_cm, waist_cm }) => {
    const h = height_cm / 100;
    const imc = Number((weight_kg / (h * h)).toFixed(1));
    const faixa = imc < 18.5 ? "Abaixo do peso" : imc < 25 ? "Peso adequado" : imc < 30 ? "Sobrepeso" : imc < 35 ? "Obesidade grau I" : imc < 40 ? "Obesidade grau II" : "Obesidade grau III";
    const riscoAbdominal = waist_cm === void 0 ? null : waist_cm > 102 ? "Muito elevado" : waist_cm > 94 ? "Elevado" : "Dentro do esperado";
    const result = {
      imc,
      faixa,
      risco_abdominal: riscoAbdominal,
      orientacao: "Resultado apenas informativo. Para um plano individualizado, fa\xE7a o Mapa Metab\xF3lico em /mapa-metabolico ou agende uma avalia\xE7\xE3o com a equipe da Dra. Bruna Durelli."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lzogolhiuhdjpqlizhxq";
var mcp_default = defineMcp({
  name: "dra-bruna-institucional",
  title: "dra-bruna-institucional",
  version: "0.1.0",
  instructions: "Ferramentas do site da Dra. Bruna Durelli. Use `clinic_info` para contato, endere\xE7o e hor\xE1rios; `list_treatments` para os tratamentos e programas oferecidos; `estimate_bmi` para um c\xE1lculo informativo de IMC e risco abdominal.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [clinic_info_default, list_treatments_default, estimate_bmi_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
